/**
 * game-core —— 前后端共用的游戏核心，12 个系统模块的聚合出口。
 *
 * 架构（v4 拆分后的形态）：
 *
 *   shared/core/util.js       工具 / 散列 / 行情时钟 / 时间常量
 *   shared/core/state.js      存档三件套（createState / hydrate / serialize）
 *   shared/core/time.js       时间档位 / 日历 / 精力 / 境界
 *   shared/core/shenshi.js    神识与分层乘区
 *   shared/core/rebirth.js    转生（兵解）/ 渡劫 / 道行加成
 *   shared/core/job.js        工作（职业）
 *   shared/core/technique.js  功法（习得 / 熟练度 / 等级 / 被动）
 *   shared/core/compute.js    设备与投向
 *   shared/core/company.js    公司 / 市场 / 行业传导 / 抛压
 *   shared/core/stock.js      股市
 *   shared/core/tick.js       核心 tick（stepTick 顺序不可打乱）
 *   shared/core/ops.js        玩家操作（服务端 /api/action 共用）
 *
 * 关键原则（与 README「技术选型说明」一致）：
 *   1) 同一份 tick：前端 100ms 实时推进、服务端离线结算，算法必须逐位一致。
 *      因此一切「随机」都是状态的纯函数（散列 / 超越函数），禁用 Math.random()。
 *   2) 四条时间线各司其职：游戏内时间（档位）/ playTime（行情时钟，marketClock）
 *      / 现实秒 dt（设备收益、投向、精力、公司周期、修炼）/ 精力（现实时间恢复，
 *      与档位解耦的产能硬上限）。行情挂现实时间是刻意设计：拉满档位不能免掉
 *      砸盘与冲击的代价。
 *   3) 模块共享命名空间 C，函数在调用期惰性解析 —— 模块间互相引用（如神识 ↔
 *      功法被动 ↔ 道行加成）不需要关心加载顺序，新增系统只要挂到 C 上即可。
 *
 * 浏览器加载：index.html 先按序引入 core/*.js（各自把工厂推入 window.__gcMods），
 * 再引入本文件执行装配；Node 端直接 require 本文件。
 */
(function (root) {
  const C = Object.create(null);

  const factoryList = (typeof require !== 'undefined' && typeof module !== 'undefined')
    ? ['./core/util.js', './core/state.js', './core/time.js', './core/shenshi.js',
       './core/rebirth.js', './core/job.js', './core/technique.js', './core/compute.js',
       './core/company.js', './core/stock.js', './core/tick.js', './core/ops.js']
        .map((p) => require(p))
    : (root.__gcMods || []);

  for (const factory of factoryList) factory(C, root);

  const API = {
    createState: C.createState,
    hydrate: C.hydrate,
    serialize: C.serialize,
    tierInfo: C.tierInfo,
    maxUnlockedTier: C.maxUnlockedTier,
    tierUnlocked: C.tierUnlocked,
    setTimeTier: C.setTimeTier,
    setAutoTier: C.setAutoTier,
    gameSecondsPerRealSecond: C.gameSecondsPerRealSecond,
    gameDate: C.gameDate,
    fmtGameDate: C.fmtGameDate,
    fmtGameDuration: C.fmtGameDuration,
    maxEnergy: C.maxEnergy,
    shenshiBase: C.shenshiBase,
    shenshiDeviceMultiplier: C.shenshiDeviceMultiplier,
    totalShenshi: C.totalShenshi,
    shenshiParts: C.shenshiParts,
    shenshiEffect: C.shenshiEffect,
    shenshiComputeMultiplier: C.shenshiComputeMultiplier,
    shenshiCultivateMultiplier: C.shenshiCultivateMultiplier,
    jobById: C.jobById,
    jobDurationSeconds: C.jobDurationSeconds,
    jobDoneCount: C.jobDoneCount,
    jobUnlocked: C.jobUnlocked,
    lockedReason: C.lockedReason,
    jobIncome: C.jobIncome,
    setJob: C.setJob,
    setWorking: C.setWorking,
    rushJob: C.rushJob,
    advanceWork: C.advanceWork,
    techById: C.techById,
    rarityById: C.rarityById,
    masteryTierOf: C.masteryTierOf,
    masteryInfo: C.masteryInfo,
    currentTech: C.currentTech,
    techRecord: C.techRecord,
    techLearned: C.techLearned,
    techUnlockConditionMet: C.techUnlockConditionMet,
    techLockedReason: C.techLockedReason,
    techCondText: C.techCondText,
    firstTechUnlocked: C.firstTechUnlocked,
    techExpCfg: C.techExpCfg,
    techExpNeed: C.techExpNeed,
    techBaseExpRate: C.techBaseExpRate,
    techExpRateOf: C.techExpRateOf,
    addTechExp: C.addTechExp,
    learnTechniques: C.learnTechniques,
    addMastery: C.addMastery,
    cultivateSpeed: C.cultivateSpeed,
    comprehendCost: C.comprehendCost,
    comprehendGain: C.comprehendGain,
    techLevel: C.techLevel,
    techMainQiSpeed: C.techMainQiSpeed,
    techniqueList: C.techniqueList,
    passiveBonus: C.passiveBonus,
    deviceCost: C.deviceCost,
    deviceStoneCost: C.deviceStoneCost,
    totalCompute: C.totalCompute,
    deviceStoneOutput: C.deviceStoneOutput,
    realComputeOf: C.realComputeOf,
    computeBreakdown: C.computeBreakdown,
    autoIncome: C.autoIncome,
    qiMultiplier: C.qiMultiplier,
    allocatableInvestments: C.allocatableInvestments,
    investmentAvailable: C.investmentAvailable,
    investmentLockReason: C.investmentLockReason,
    investOutput: C.investOutput,
    investOutputRate: C.investOutputRate,
    hardwareCostFactor: C.hardwareCostFactor,
    investedHardwareOf: C.investedHardwareOf,
    hasAnyTechnique: C.hasAnyTechnique,
    goodCurrency: C.goodCurrency,
    stoneExchangeRate: C.stoneExchangeRate,
    setAllocationShare: C.setAllocationShare,
    stockAccessible: C.stockAccessible,
    stockAccessReason: C.stockAccessReason,
    techCondProgress: C.techCondProgress,
    realmInfo: C.realmInfo,
    nextRealm: C.nextRealm,
    techniqueUnlocked: C.techniqueUnlocked,
    spiritAllowed: C.spiritAllowed,
    fmtBig: C.fmtBig,
    lineById: C.lineById,
    goodById: C.goodById,
    goodsPrice: C.goodsPrice,
    goodsTrend: C.goodsTrend,
    goodsNextChangeIn: C.goodsNextChangeIn,
    goodsPeriodSeconds: C.goodsPeriodSeconds,
    goodsPeriod: C.goodsPeriod,
    goodsSeries: C.goodsSeries,
    goodsWindow: C.goodsWindow,
    marketCfg: C.marketCfg,
    pressureOf: C.pressureOf,
    excessSold: C.excessSold,
    pressureAdd: C.pressureAdd,
    marketImpactAt: C.marketImpactAt,
    goodsPriceWith: C.goodsPriceWith,
    goodsSeriesWith: C.goodsSeriesWith,
    goodsWindowWith: C.goodsWindowWith,
    marketDropRatio: C.marketDropRatio,
    naturalPrice: C.naturalPrice,
    syncMarket: C.syncMarket,
    marketSummary: C.marketSummary,
    marketFloorPrice: C.marketFloorPrice,
    companyFounded: C.companyFounded,
    companyUnlocked: C.companyUnlocked,
    companyLockedReason: C.companyLockedReason,
    warehouseLevel: C.warehouseLevel,
    warehouseCapacity: C.warehouseCapacity,
    warehouseCost: C.warehouseCost,
    stockTotal: C.stockTotal,
    stockOf: C.stockOf,
    lineOwned: C.lineOwned,
    lineUnlocked: C.lineUnlocked,
    lineLockedReason: C.lineLockedReason,
    lineCost: C.lineCost,
    companyUpkeep: C.companyUpkeep,
    companyOutputPerCycle: C.companyOutputPerCycle,
    companyCycleGross: C.companyCycleGross,
    companyCycleNet: C.companyCycleNet,
    companyFinance: C.companyFinance,
    sellAllWithPrices: C.sellAllWithPrices,
    companyIncomePerSecond: C.companyIncomePerSecond,
    syncCompany: C.syncCompany,
    industryById: C.industryById,
    goodsOfIndustry: C.goodsOfIndustry,
    lineProducts: C.lineProducts,
    lineIndustry: C.lineIndustry,
    industryPriceRatio: C.industryPriceRatio,
    industryUpstreamRatio: C.industryUpstreamRatio,
    industryPriceIndex: C.industryPriceIndex,
    industryCostIndex: C.industryCostIndex,
    industrialComputePool: C.industrialComputePool,
    lineUnits: C.lineUnits,
    lineMinRate: C.lineMinRate,
    unitActive: C.unitActive,
    companyComputeDemand: C.companyComputeDemand,
    companyComputeScale: C.companyComputeScale,
    companyComputeTiers: C.companyComputeTiers,
    unitComputeScale: C.unitComputeScale,
    unitOutput: C.unitOutput,
    setLineUnit: C.setLineUnit,
    setIndustryRate: C.setIndustryRate,
    linePriority: C.linePriority,
    setLinePriority: C.setLinePriority,
    stockCfg: C.stockCfg,
    stockById: C.stockById,
    stockUnlocked: C.stockUnlocked,
    stockLockedReason: C.stockLockedReason,
    stockDepth: C.stockDepth,
    stockPeriodSeconds: C.stockPeriodSeconds,
    stockPeriod: C.stockPeriod,
    stockFactor: C.stockFactor,
    stockLinkFactor: C.stockLinkFactor,
    stockShares: C.stockShares,
    stockFlow: C.stockFlow,
    stockCost: C.stockCost,
    stockAvgCost: C.stockAvgCost,
    stockHeldRatio: C.stockHeldRatio,
    stockImpact: C.stockImpact,
    stockImpactAt: C.stockImpactAt,
    stockNaturalPrice: C.stockNaturalPrice,
    stockPrice: C.stockPrice,
    stockTrend: C.stockTrend,
    stockNextChangeIn: C.stockNextChangeIn,
    stockSeries: C.stockSeries,
    stockWindow: C.stockWindow,
    stockForecastPct: C.stockForecastPct,
    stockHoldingValue: C.stockHoldingValue,
    stockHoldingPnl: C.stockHoldingPnl,
    stockBuyQuote: C.stockBuyQuote,
    stockSellQuote: C.stockSellQuote,
    stockMaxBuy: C.stockMaxBuy,
    buyStock: C.buyStock,
    sellStock: C.sellStock,
    syncStocks: C.syncStocks,
    stockSummary: C.stockSummary,
    marketClock: C.marketClock,
    rebirthCfg: C.rebirthCfg,
    rebirthState: C.rebirthState,
    rebirthCount: C.rebirthCount,
    rebirthDiscount: C.rebirthDiscount,
    rebirthFactorAt: C.rebirthFactorAt,
    rebirthAttenuate: C.rebirthAttenuate,
    rebirthComputeCap: C.rebirthComputeCap,
    deviceComputeEffective: C.deviceComputeEffective,
    rebirthSummary: C.rebirthSummary,
    rebirthDaoGain: C.rebirthDaoGain,
    rebirthUnlocked: C.rebirthUnlocked,
    rebirthLockedReason: C.rebirthLockedReason,
    doRebirth: C.doRebirth,
    perkById: C.perkById,
    perkLevel: C.perkLevel,
    perkValue: C.perkValue,
    perkCost: C.perkCost,
    buyPerk: C.buyPerk,
    tribulationCfg: C.tribulationCfg,
    tribulationState: C.tribulationState,
    tribulationLevel: C.tribulationLevel,
    tribulationBonus: C.tribulationBonus,
    tribulationComputeBase: C.tribulationComputeBase,
    perfectedTechniqueCount: C.perfectedTechniqueCount,
    tribulationOdds: C.tribulationOdds,
    tribulationReady: C.tribulationReady,
    tribulationRoll: C.tribulationRoll,
    tribulationBoonSummary: C.tribulationBoonSummary,
    tribulationSummary: C.tribulationSummary,
    doTribulation: C.doTribulation,
    setAutoTribulation: C.setAutoTribulation,
    energyRegen: C.energyRegen,
    setTimePaused: C.setTimePaused,
    offlineRatio: C.offlineRatio,
    offlineMaxHours: C.offlineMaxHours,
    stockFee: C.stockFee,
    tick: C.tick,
    buyDevice: C.buyDevice,
    setAllocation: C.setAllocation,
    setTechnique: C.setTechnique,
    setCultivating: C.setCultivating,
    comprehend: C.comprehend,
    foundCompany: C.foundCompany,
    buyLine: C.buyLine,
    upgradeWarehouse: C.upgradeWarehouse,
    sellGoods: C.sellGoods,
    setAutoSell: C.setAutoSell,
    previewOffline: C.previewOffline,
    SEC_PER_MIN: C.SEC_PER_MIN,
    SEC_PER_HOUR: C.SEC_PER_HOUR,
    SEC_PER_DAY: C.SEC_PER_DAY,
    SEC_PER_MONTH: C.SEC_PER_MONTH,
    SEC_PER_YEAR: C.SEC_PER_YEAR,
    DAYS_PER_YEAR: C.DAYS_PER_YEAR,
    PERFECT_TIER: C.PERFECT_TIER,
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = API;
  if (typeof window !== 'undefined') root.GameCore = API;
})(typeof window !== 'undefined' ? window : globalThis);
