    /** 前端榜单只显示市值最高的前 N 家（其余留在池子里，留给后续收购） */
    boardSize: 10,

    /**
     * 上市公司表 —— 30 家科技 + 20 家修仙（宗门）。
     *
     *   kind       tech = 科技公司，xiuxian = 修仙宗门
     *   sector     主营行业（对应 company.industries）
     *   link       联动的商品 id（null = 独立行情，不受商品市场影响）
     *   business   主营业务 —— 前端每行都显示它，行情一动就能看出波及谁
     *   depth      流通盘（股）
     *   periodYears 变价周期（游戏内年）
     *
     * 价格量级刻意比联动商品**低几个数量级**：一股的价钱不等于一件货的价钱，
     * 否则洞天类公司一股要 1e12，早期玩家永远开不了仓。同时流通盘按「目标市值
     * ≈ 1e11」反推，让 50 家的市值落在同一档 —— 榜单前 10 才会随行情真的换人。
     */
    stocks: [
      // ================= 科技 · 采掘（4）=================
      { id: 'jinshi', name: '金石矿业', code: 'JINSHI', kind: 'tech', sector: 'mining', link: 'iron_ore',
        business: '铁矿石开采与粗选', basePrice: 45, volatility: 1.05, minFactor: 0.34, maxFactor: 2.90, depth: 2.2e9, periodYears: 1,
        desc: '守着半座铁矿山过日子。钢价涨它未必涨，矿价跌它一定跌。' },
      { id: 'beiling', name: '北岭煤业', code: 'BEILING', kind: 'tech', sector: 'mining', link: 'coal',
        business: '焦煤开采与洗选', basePrice: 38, volatility: 1.00, minFactor: 0.36, maxFactor: 2.75, depth: 2.4e9, periodYears: 1,
        desc: '给所有高炉供口粮。口粮一贵，全产业链都跟着咳嗽。' },
      { id: 'chitong', name: '赤铜集团', code: 'CHITONG', kind: 'tech', sector: 'mining', link: 'copper_ore',
        business: '铜矿石采选', basePrice: 62, volatility: 1.10, minFactor: 0.33, maxFactor: 3.00, depth: 1.6e9, periodYears: 1,
        desc: '电线、电机、散热片都吃铜。它的报表就是基建的体温计。' },
      { id: 'xitu', name: '稀土纪元', code: 'XITU', kind: 'tech', sector: 'mining', link: 'rare_earth',
        business: '稀土矿开采与分离', basePrice: 180, volatility: 1.35, minFactor: 0.26, maxFactor: 3.80, depth: 4.4e8, periodYears: 1,
        desc: '一吨矿里的那几克，卡着整个高端制造的脖子。涨起来没有道理可讲。' },
      // ================= 科技 · 冶炼（4）=================
      { id: 'rongcheng', name: '熔城冶金', code: 'RONGCHENG', kind: 'tech', sector: 'smelt', link: 'pig_iron',
        business: '生铁冶炼', basePrice: 55, volatility: 0.98, minFactor: 0.37, maxFactor: 2.65, depth: 1.8e9, periodYears: 1,
        desc: '高炉日夜不熄火。矿价是它最大的敌人，钢价是它唯一的指望。' },
      { id: 'changhe', name: '长河钢铁', code: 'CHANGHE', kind: 'tech', sector: 'smelt', link: 'steel',
        business: '钢材轧制', basePrice: 95, volatility: 0.95, minFactor: 0.38, maxFactor: 2.55, depth: 1.1e9, periodYears: 1,
        desc: '基建的米铺子。毛利率薄得像钢板，全靠走量。' },
      { id: 'qingjin', name: '轻金属联合', code: 'QINGJIN', kind: 'tech', sector: 'smelt', link: 'aluminum',
        business: '铝锭电解', basePrice: 130, volatility: 1.00, minFactor: 0.36, maxFactor: 2.70, depth: 8.0e8, periodYears: 1,
        desc: '电解槽一开就是几个月不停。电价涨一分，利润就没了。' },
      { id: 'jinggui', name: '晶硅科技', code: 'JINGGUI', kind: 'tech', sector: 'smelt', link: 'silicon_met',
        business: '工业硅提纯', basePrice: 240, volatility: 1.15, minFactor: 0.32, maxFactor: 3.05, depth: 3.6e8, periodYears: 1,
        desc: '光伏与芯片的共同上游。两头景气它最风光，两头萧条它最先倒。' },
      // ================= 科技 · 化工（4）=================
      { id: 'sansuan', name: '三酸化建', code: 'SANSUAN', kind: 'tech', sector: 'chem', link: 'sulfuric',
        business: '硫酸与基础化工', basePrice: 70, volatility: 0.92, minFactor: 0.39, maxFactor: 2.45, depth: 1.5e9, periodYears: 1,
        desc: '化工里的自来水厂。哪里都要，哪里都不值钱 —— 胜在稳定。' },
      { id: 'dangu', name: '氮谷化工', code: 'DANGU', kind: 'tech', sector: 'chem', link: 'ammonia',
        business: '合成氨与氮肥', basePrice: 110, volatility: 0.95, minFactor: 0.38, maxFactor: 2.50, depth: 9.0e8, periodYears: 1,
        desc: '养活一半人口的产业。需求刚性，价格也就没什么想象力。' },
      { id: 'teqi', name: '特气先锋', code: 'TEQI', kind: 'tech', sector: 'chem', link: 'spec_gas',
        business: '特种气体', basePrice: 320, volatility: 1.12, minFactor: 0.33, maxFactor: 2.95, depth: 3.0e8, periodYears: 1,
        desc: '纯度写进小数点后六位。客户一旦认证就不换供应商，也不还价。' },
      { id: 'guangke', name: '光刻材料', code: 'GUANGKE', kind: 'tech', sector: 'chem', link: 'photoresist',
        business: '光刻胶与电子化学品', basePrice: 620, volatility: 1.30, minFactor: 0.28, maxFactor: 3.55, depth: 1.6e8, periodYears: 1,
        desc: '卡脖子的那瓶液体。国产替代的故事讲了很多年，每次都能涨一轮。' },
      // ================= 科技 · 精密制造（5）=================
      { id: 'jinggong', name: '精工轴承', code: 'JINGGONG', kind: 'tech', sector: 'precision', link: 'bearing',
        business: '高精度轴承', basePrice: 380, volatility: 0.90, minFactor: 0.40, maxFactor: 2.40, depth: 2.6e8, periodYears: 1,
        desc: '所有转动的东西都要它。寿命按万小时算，口碑按十年攒。' },
      { id: 'wanxiang', name: '万象传动', code: 'WANXIANG', kind: 'tech', sector: 'precision', link: 'gearbox',
        business: '齿轮组与传动系统', basePrice: 520, volatility: 0.92, minFactor: 0.40, maxFactor: 2.42, depth: 2.0e8, periodYears: 1,
        desc: '把转速变成扭矩的生意。机床、风电、机器人，处处有它的齿轮。' },
      { id: 'hengyue', name: '恒岳重工', code: 'HENGYUE', kind: 'tech', sector: 'precision', link: 'hydraulic',
        business: '液压件与重型装备', basePrice: 700, volatility: 0.94, minFactor: 0.39, maxFactor: 2.45, depth: 1.5e8, periodYears: 1,
        desc: '挖掘机的大臂、水轮机的闸门。订单跟着基建周期大起大落。' },
      { id: 'tiangong', name: '天工模具', code: 'TIANGONG', kind: 'tech', sector: 'precision', link: 'mold',
        business: '精密模具', basePrice: 900, volatility: 0.95, minFactor: 0.39, maxFactor: 2.48, depth: 1.2e8, periodYears: 1,
        desc: '一套模具定一款产品的命。做得准就能吃十年，做不准就是废铁。' },
      { id: 'mingjing', name: '明镜光学', code: 'MINGJING', kind: 'tech', sector: 'precision', link: 'optics',
        business: '光学镜片与镜头组', basePrice: 1500, volatility: 1.08, minFactor: 0.35, maxFactor: 2.80, depth: 6.5e7, periodYears: 1,
        desc: '镜头里的玻璃比金贵。镀膜配方是它唯一不写在说明书上的东西。' },
      // ================= 科技 · 电子（6）=================
      { id: 'yuanjian', name: '元件世家', code: 'YUANJIAN', kind: 'tech', sector: 'electron', link: 'component',
        business: '被动元件与连接器', basePrice: 1200, volatility: 1.05, minFactor: 0.36, maxFactor: 2.75, depth: 8.5e7, periodYears: 1,
        desc: '一颗几分钱，缺货时整条产线停摆。周期来了涨十倍，走了跌回原地。' },
      { id: 'gonglv', name: '功率半导体', code: 'GONGLV', kind: 'tech', sector: 'electron', link: 'power_dev',
        business: '功率器件', basePrice: 2100, volatility: 1.10, minFactor: 0.34, maxFactor: 2.85, depth: 4.8e7, periodYears: 1,
        desc: '电车与电网的心脏。不追先进制程，靠可靠性吃一辈子。' },
      { id: 'ganxin', name: '感芯科技', code: 'GANXIN', kind: 'tech', sector: 'electron', link: 'sensor',
        business: '传感器', basePrice: 3200, volatility: 1.15, minFactor: 0.33, maxFactor: 2.95, depth: 3.2e7, periodYears: 1,
        desc: '给机器装五官。出货量跟着终端走，毛利率跟着竞争格局走。' },
      { id: 'cunchu', name: '存储纪元', code: 'CUNCHU', kind: 'tech', sector: 'electron', link: 'memory_die',
        business: '存储颗粒', basePrice: 3000, volatility: 1.28, minFactor: 0.29, maxFactor: 3.40, depth: 3.4e7, periodYears: 1,
        desc: '标准的周期股。三年不开张，开张吃三年，散户在这上面亏得最惨。' },
      { id: 'guanglian', name: '光联通信', code: 'GUANGLIAN', kind: 'tech', sector: 'electron', link: 'optical_mod',
        business: '光模块', basePrice: 4500, volatility: 1.20, minFactor: 0.31, maxFactor: 3.20, depth: 2.3e7, periodYears: 1,
        desc: '算力集群的血管。数据中心一扩建，它的订单就排到明年。' },
      { id: 'chipsci', name: '算力芯科', code: 'CHIPSCI', kind: 'tech', sector: 'electron', link: 'chip',
        business: '半导体芯片设计与代工', basePrice: 5200, volatility: 1.25, minFactor: 0.30, maxFactor: 3.30, depth: 2.0e7, periodYears: 1,
        desc: '给整机厂供芯的老牌大厂。芯片行情好它就涨，行情差它就跌 —— 很诚实。' },
      // ================= 科技 · 整机装配（6）=================
      { id: 'xuanji', name: '玄机数术', code: 'XUANJI', kind: 'tech', sector: 'assembly', link: 'server',
        business: '服务器整机与算力集群', basePrice: 8000, volatility: 1.00, minFactor: 0.38, maxFactor: 2.60, depth: 1.3e7, periodYears: 1,
        desc: '整机与算力集群的承包商。订单跟着服务器行情走，账期跟着甲方走。' },
      { id: 'jixie', name: '机械纪元', code: 'JIXIE', kind: 'tech', sector: 'assembly', link: 'robot',
        business: '工业机器人', basePrice: 12000, volatility: 1.05, minFactor: 0.36, maxFactor: 2.70, depth: 8.5e6, periodYears: 1,
        desc: '替代人工的那批铁臂。人力越贵它越好卖，需求很朴素。' },
      { id: 'jiqun', name: '集群时代', code: 'JIQUN', kind: 'tech', sector: 'assembly', link: 'cabinet',
        business: '算力集群集成', basePrice: 15000, volatility: 1.08, minFactor: 0.35, maxFactor: 2.78, depth: 7.0e6, periodYears: 1,
        desc: '把机柜、供电、液冷打包交付。真正的门槛是交付速度，不是技术。' },
      { id: 'ruifeng', name: '锐锋机床', code: 'RUIFENG', kind: 'tech', sector: 'assembly', link: 'cnc',
        business: '精密数控机床', basePrice: 22000, volatility: 1.02, minFactor: 0.37, maxFactor: 2.62, depth: 4.6e6, periodYears: 1,
        desc: '工业母机。所有精密件的精度，最终都由它的丝杠决定。' },
      { id: 'yinghe', name: '影和医疗', code: 'YINGHE', kind: 'tech', sector: 'assembly', link: 'imaging',
        business: '医学影像设备', basePrice: 28000, volatility: 0.98, minFactor: 0.38, maxFactor: 2.55, depth: 3.6e6, periodYears: 1,
        desc: 'CT 与核磁。招标周期长、回款慢，但一旦中标就是十年服务。' },
      { id: 'xingcha', name: '星槎航天', code: 'XINGCHA', kind: 'tech', sector: 'assembly', link: 'sat_bus',
        business: '卫星平台与载荷', basePrice: 42000, volatility: 1.22, minFactor: 0.30, maxFactor: 3.25, depth: 2.5e6, periodYears: 1,
        desc: '把东西送上天，还要它回来。一次失利，股价腰斩；一次成功，翻倍。' },
      // ================= 科技 · 独立行情（1）=================
      { id: 'tianji', name: '天机阁', code: 'TIANJI', kind: 'tech', sector: null, link: null,
        business: '推演与咨询（无从核实）', basePrice: 60, volatility: 1.45, minFactor: 0.24, maxFactor: 4.20, depth: 1.8e9, periodYears: 1,
        desc: '坊间传它算得出天机。既算不出自己的现金流，也算不出下个月还在不在。' },
      // ================= 修仙 · 灵植（4）=================
      { id: 'qinghe', name: '青禾灵田', code: 'QINGHE', kind: 'xiuxian', sector: 'herb', link: 'spirit_grain',
        business: '灵谷种植与仓储', basePrice: 260, volatility: 0.80, minFactor: 0.44, maxFactor: 2.20, depth: 4.0e8, periodYears: 1,
        desc: '修仙界的口粮供应商。谁都要吃饭，所以谁也不敢让它倒。' },
      { id: 'yunma', name: '云麻堂', code: 'YUNMA', kind: 'xiuxian', sector: 'herb', link: 'spirit_hemp',
        business: '灵麻与纤维作物', basePrice: 380, volatility: 0.82, minFactor: 0.43, maxFactor: 2.22, depth: 2.7e8, periodYears: 1,
        desc: '符纸与法袍都从它这里起。制符业景气，它的地里就全是订单。' },
      { id: 'yuehua', name: '月华药圃', code: 'YUEHUA', kind: 'xiuxian', sector: 'herb', link: 'moon_herb',
        business: '月华草等灵草栽培', basePrice: 650, volatility: 0.85, minFactor: 0.42, maxFactor: 2.28, depth: 1.6e8, periodYears: 1,
        desc: '丹房的头号供应商。灵草一歉收，下游丹价立刻跳。' },
      { id: 'xuanbing', name: '玄冰谷', code: 'XUANBING', kind: 'xiuxian', sector: 'herb', link: 'frost_lotus',
        business: '玄冰花等寒性灵植', basePrice: 980, volatility: 0.90, minFactor: 0.41, maxFactor: 2.35, depth: 1.05e8, periodYears: 1,
        desc: '谷里终年不化雪。寒性灵材九成出自此处，也就九成的定价权。' },
      // ================= 修仙 · 炼丹（4）=================
      { id: 'cuiti', name: '淬体堂', code: 'CUITI', kind: 'xiuxian', sector: 'alchemy', link: 'body_pill',
        business: '淬体丹批量炼制', basePrice: 900, volatility: 0.75, minFactor: 0.46, maxFactor: 2.12, depth: 1.15e8, periodYears: 1,
        desc: '最低端的丹，也是销量最大的丹。薄利多销，靠自动化产线活。' },
      { id: 'danxia', name: '丹霞生物', code: 'DANXIA', kind: 'xiuxian', sector: 'alchemy', link: 'heal_pill',
        business: '疗伤丹与常备丹药', basePrice: 1800, volatility: 0.78, minFactor: 0.45, maxFactor: 2.18, depth: 5.8e7, periodYears: 1,
        desc: '把炼丹做成工艺的医药巨头。一粒丹的毛利率，够养活整条产业链。' },
      { id: 'xisui', name: '洗髓宗', code: 'XISUI', kind: 'xiuxian', sector: 'alchemy', link: 'marrow_pill',
        business: '洗髓丹与体质改造', basePrice: 3200, volatility: 0.82, minFactor: 0.44, maxFactor: 2.25, depth: 3.2e7, periodYears: 1,
        desc: '改资质的丹，卖的是希望。涨价不需要理由，跌价只需要一次事故。' },
      { id: 'jindan', name: '金丹阁', code: 'JINDAN', kind: 'xiuxian', sector: 'alchemy', link: 'golden_pill',
        business: '九转金丹等高端丹药', basePrice: 6800, volatility: 0.95, minFactor: 0.40, maxFactor: 2.45, depth: 1.5e7, periodYears: 1,
        desc: '一丹难求。产量以「炉」计，客户以「宗门」计，价格从不明码。' },
      // ================= 修仙 · 制符（3）=================
      { id: 'qingfeng', name: '清风符社', code: 'QINGFENG', kind: 'xiuxian', sector: 'talisman', link: 'wind_talis',
        business: '清风符等日用符箓', basePrice: 750, volatility: 0.76, minFactor: 0.46, maxFactor: 2.14, depth: 1.4e8, periodYears: 1,
        desc: '日用符里的日用品。赚的是复购，不是溢价。' },
      { id: 'leifu', name: '雷符门', code: 'LEIFU', kind: 'xiuxian', sector: 'talisman', link: 'thunder_tal',
        business: '雷符与攻伐符箓', basePrice: 4500, volatility: 0.88, minFactor: 0.42, maxFactor: 2.32, depth: 2.3e7, periodYears: 1,
        desc: '斗法用的消耗品。宗门摩擦一多，它的库存就见底。' },
      { id: 'tiandun', name: '天遁符宗', code: 'TIANDUN', kind: 'xiuxian', sector: 'talisman', link: 'teleport_tal',
        business: '传送符与空间符阵', basePrice: 8000, volatility: 0.96, minFactor: 0.40, maxFactor: 2.48, depth: 1.3e7, periodYears: 1,
        desc: '空间一道，自古独门。会做的人少，敢买的人多。' },
      // ================= 修仙 · 炼器（4）=================
      { id: 'cangfeng', name: '藏锋阁', code: 'CANGFENG', kind: 'xiuxian', sector: 'refine', link: 'magic_sword',
        business: '法剑锻制', basePrice: 2600, volatility: 0.85, minFactor: 0.43, maxFactor: 2.28, depth: 4.0e7, periodYears: 1,
        desc: '一名剑修一把剑，藏锋阁供了三成。剑修越多，它越稳。' },
      { id: 'xuanjia', name: '玄甲宗', code: 'XUANJIA', kind: 'xiuxian', sector: 'refine', link: 'armor',
        business: '护甲与防具', basePrice: 5200, volatility: 0.88, minFactor: 0.42, maxFactor: 2.32, depth: 2.0e7, periodYears: 1,
        desc: '护具这门生意，跟着「谁在打仗」走。和平年代它就卖农具。' },
      { id: 'feizhou', name: '飞舟坊', code: 'FEIZHOU', kind: 'xiuxian', sector: 'refine', link: 'flying_boat',
        business: '飞舟与载具', basePrice: 12000, volatility: 0.92, minFactor: 0.41, maxFactor: 2.38, depth: 8.6e6, periodYears: 1,
        desc: '从货运到远游都靠它。灵脉航线开到哪里，它的订单就到哪。' },
      { id: 'benming', name: '本命斋', code: 'BENMING', kind: 'xiuxian', sector: 'refine', link: 'core_treasure',
        business: '本命法宝温养', basePrice: 35000, volatility: 1.05, minFactor: 0.37, maxFactor: 2.70, depth: 3.0e6, periodYears: 1,
        desc: '一人一件，温养百年。客户终身只来一次，客单价高得离谱。' },
      // ================= 修仙 · 阵盘（3）=================
      { id: 'panshi', name: '磐石阵门', code: 'PANSHI', kind: 'xiuxian', sector: 'array', link: 'ward_array',
        business: '防护阵盘', basePrice: 6500, volatility: 0.88, minFactor: 0.42, maxFactor: 2.30, depth: 1.6e7, periodYears: 1,
        desc: '护山大阵的承办方。宗门只要还在，它的维护合同就续。' },
      { id: 'huanzhen', name: '幻阵阁', code: 'HUANZHEN', kind: 'xiuxian', sector: 'array', link: 'illusion_arr',
        business: '幻阵与迷阵', basePrice: 18000, volatility: 0.95, minFactor: 0.40, maxFactor: 2.45, depth: 5.8e6, periodYears: 1,
        desc: '卖的是「看不穿」。秘境一开，它的阵盘就脱销。' },
      { id: 'zhoutian', name: '周天阵宗', code: 'ZHOUTIAN', kind: 'xiuxian', sector: 'array', link: 'star_array',
        business: '周天星斗大阵', basePrice: 60000, volatility: 1.10, minFactor: 0.36, maxFactor: 2.85, depth: 1.75e6, periodYears: 1,
        desc: '一套阵护一宗千年。做不了假的生意，也就没有价格战。' },
      // ================= 修仙 · 洞天（2）=================
      { id: 'lingmai', name: '灵脉能源', code: 'LINGMAI', kind: 'xiuxian', sector: 'cave', link: 'leyline_node',
        business: '灵脉节点与供能', basePrice: 90000, volatility: 0.98, minFactor: 0.39, maxFactor: 2.55, depth: 1.2e6, periodYears: 1,
        desc: '握着灵脉的能源寡头。阵盘卖得越好，它的电价越硬 —— 直到有人找到第二条灵脉。' },
      { id: 'taixu', name: '太虚洞天', code: 'TAIXU', kind: 'xiuxian', sector: 'cave', link: 'cave_heaven',
        business: '洞天开凿与小世界营造', basePrice: 200000, volatility: 1.15, minFactor: 0.34, maxFactor: 3.00, depth: 5.4e5, periodYears: 1,
        desc: '卖天地的公司。每开出一方洞天，就多一处可以收租的世界。' },
    ],
